baseURL = "http://localhost:3000/"
languageCode = "en-us"
title = "Octopus, 8 ways"
theme = "eureka"

paginate = 3
copyright = "Matthew Cloud 2021"
enableEmoji = true
enableGitInfo = false
summaryLength = 100

defaultContentLanguage = "en"
defaultContentLangugeInSubdir = "en"


[markup]
  [markup.highlight]
    codeFences = false
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

staticDir = ["static"]